#pragma once
#include <shinobi.h>


typedef struct _anon5 _anon5;
typedef struct Camera Camera;
typedef struct _anon30 _anon30;
typedef struct _anon45 _anon45;

struct _anon5 {
    unsigned int flg;
    unsigned int obj_num;
    void* datP;
    NJS_OBJECT* objP;
    NJS_TEXLIST* texP;
    OBJECT_WORK* owP;
};

struct BH_PWORK {
    unsigned int flg;
    unsigned short id;
    unsigned short type;
    char flr_no;
    char flr_nob;
    unsigned char mdlver;
    unsigned char param;
    unsigned char mode0;
    unsigned char mode1;
    unsigned char mode2;
    unsigned char mode3;
    float px;
    float py;
    float pz;
    int ax;
    int ay;
    int az;
    float ar;
    float aw;
    float ah;
    float ad;
    float car;
    float cah;
    float pxb;
    float pyb;
    float pzb;
    int axb;
    int ayb;
    int azb;
    float gpx;
    float gpy;
    float gpz;
    float lox;
    float loy;
    float loz;
    float aox;
    float aoy;
    float aoz;
    float spd;
    unsigned int flg2;
    unsigned int mdflg;
    unsigned int stflg;
    unsigned int Dummy3;
    int draw_tp;
    int mdl_n;
    void* mskp;
    unsigned int Dummy[1];
    int* skp[16];
    NJS_OBJECT* mbp[16];
    NJS_TEXLIST* txp[16];
    _anon5 mdl[16];
    _anon5* mlwP;
    unsigned int mdl_no;
    int lkono;
    unsigned char* lkwkp;
    unsigned char* exp0;
    unsigned char* exp1;
    unsigned char* exp2;
    unsigned char* exp3;
    unsigned char mtxbuf[64];
    NJS_MATRIX mtx;
    NJS_OBJECT* obj_a;
    NJS_OBJECT* obj_b;
    float shp_ct;
    char clp_jno[8];
    int lok_jno;
    Unknown2* mnwP;
    Unknown2* mnwPb;
    unsigned int mtn_attr;
    unsigned int mtn_no;
    int frm_no;
    unsigned int frm_mode;
    int hokan_rate;
    unsigned int hokan_count;
    unsigned int hokan_ctbak;
    int mtn_add;
    unsigned int mtn_md;
    unsigned char* mtn_tp;
    int axp;
    int ayp;
    int azp;
    short psh_ct;
    short psh_idx;
    int idx_ct;
    int mtn_chk;
    float ofx;
    float ofy;
    float ofz;
    float sx;
    float sy;
    float sz;
    float sxb;
    float syb;
    float szb;
    float xn;
    float yn;
    float zn;
    int ct0;
    int ct1;
    int ct2;
    int ct3;
    int wpnr_no;
    int wpnl_no;
    unsigned int at_flg;
    NJS_CAPSULE watr;
    Unknown18* cpcl;
    short wax;
    short way;
    short waz;
    short waxp;
    short wayp;
    short wazp;
    int hp;
    int dam[64];
    int djnt_no;
    int cpcl_no;
    int dax;
    int day;
    float dpx;
    float dpy;
    float dpz;
    float dvx;
    float dvy;
    float dvz;
    int flr_snd;
    int ko_num;
    int footeff;
    int src_no;
    unsigned char* kdnp;
    int kdnidx;
    void* dan_ap;
    unsigned int comb_flg;
    unsigned int comb_wep;
    int comb_pnt;
    int comb_timeout;
    int total_dam;
    unsigned int Dummy2[2];
};


struct Unknown1 
{
    unsigned int flg;
    unsigned short id;
    unsigned short type;
    char flr_no;
    char flr_nob;
    unsigned char mdlver;
    unsigned char param;
    unsigned char mode0;
    unsigned char mode1;
    unsigned char mode2;
    unsigned char mode3;
    float px;
    float py;
    float pz;
    int ax;
    int ay;
    int az;
    float ar;
    float aw;
    float ah;
    float ad;
    float car;
    float cah;
    float pxb;
    float pyb;
    float pzb;
    int axb;
    int ayb;
    int azb;
    float gpx;
    float gpy;
    float gpz;
    float lox;
    float loy;
    float loz;
    float aox;
    float aoy;
    float aoz;
    float spd;
    unsigned int flg2;
    unsigned int mdflg;
    unsigned int stflg;
    unsigned int Dummy3;
    int draw_tp;
    int mdl_n;
    void* mskp;
    unsigned int Dummy[1];
    int* skp[16];
    NJS_OBJECT* mbp[16];
    NJS_TEXLIST* txp[16];
    _anon5 mdl[16];
    _anon5* mlwP;
    unsigned int mdl_no;
    int lkono;
    unsigned char* lkwkp;
    unsigned char* exp0;
    unsigned char* exp1;
    unsigned char* exp2;
    unsigned char* exp3;
    unsigned char mtxbuf[64];
    NJS_MATRIX mtx;
    NJS_OBJECT* obj_a;
    NJS_OBJECT* obj_b;
    float shp_ct;
    char clp_jno[8];
    int lok_jno;
    Unknown2* mnwP;
    Unknown2* mnwPb;
    unsigned int mtn_attr;
    unsigned int mtn_no;
    int frm_no;
    unsigned int frm_mode;
    int hokan_rate;
    unsigned int hokan_count;
    unsigned int hokan_ctbak;
    int mtn_add;
    unsigned int mtn_md;
    unsigned char* mtn_tp;
    int axp;
    int ayp;
    int azp;
    short psh_ct;
    short psh_idx;
    int idx_ct;
    int mtn_chk;
    float ofx;
    float ofy;
    float ofz;
    float sx;
    float sy;
    float sz;
    float sxb;
    float syb;
    float szb;
    float xn;
    float yn;
    float zn;
    int ct0;
    int ct1;
    int ct2;
    int ct3;
    unsigned char* objbak;
    NJS_SPHERE cspr;
    int pn;
    NJS_POLYGON_VTX* pvp;
    NJS_TEXTURE_VTX* tvp;
    NJS_POLYGON_VTX pv[4];
    NJS_TEXTURE_VTX tv[4];
    int bl_src;
    int bl_dst;
    int ani_ct;
    int tex_id;
    int aspd;
    unsigned int gidx;
    int bank;
    char jno[16];
    char hide[4];
    void (*func)(void*);
    int idx;
    int Dummy2;
};


struct _anon45 {
    NJS_MATRIX m;
    float px;
    float py;
    float pz;
    float vx;
    float vy;
    float vz;
    int roll;
    float apx;
    float apy;
    float apz;
    float avx;
    float avy;
    float avz;
    int aroll;
};
